// ===== INTERNATIONALIZATION (i18n) =====
// Mặc định: 'vi' (tiếng Việt)

const I18N = {
  vi: {
    // Header
    page_title:       "Tổng hợp thị trường hàng ngày",
    page_subtitle_pre: "Cập nhật lần cuối:",
    page_source:      "Nguồn: Yahoo Finance · FRED",
    btn_refresh:      "Refresh",

    // Summary pills
    pill_danger:   (n) => `${n} Cảnh báo`,
    pill_warning:  (n) => `${n} Cảnh giác`,
    pill_success:  (n) => `${n} Bình thường`,

    // Risk card
    risk_title:       "TỔNG ĐIỂM RỦI RO",
    risk_history_label: "Lịch sử điểm rủi ro 30 ngày",
    table_title:      "Chi tiết các chỉ báo rủi ro",
    gl_0: "0–35 An toàn",
    gl_1: "36–55 Thận trọng",
    gl_2: "56–75 Cảnh báo",
    gl_3: "76–100 Nguy hiểm",
    bd_geo:    "Địa chính trị",
    bd_inst:   "Dòng tiền tổ chức",
    bd_market: "Thị trường",
    bd_macro:  "Vĩ mô",
    bd_mult:   "Hệ số khuếch đại",
    bd_leads_title: "Lead indicators kích hoạt:",
    bd_geo_w:    "(15%)",
    bd_inst_w:   "(25%)",
    bd_market_w: "(40%)",
    bd_macro_w:  "(20%)",

    // Risk table
    risk_th_range:  "Mức điểm",
    risk_th_meaning:"Ý nghĩa",
    risk_th_action: "Hành động",
    risk_rows: [
      { range: "0–35",   level: "BÌNH THƯỜNG",     action: "Duy trì tỷ trọng, theo dõi định kỳ" },
      { range: "36–55",  level: "CẢNH GIÁC",        action: "Giảm đòn bẩy, chuẩn bị phòng vệ" },
      { range: "56–75",  level: "CẢNH BÁO CAO",     action: "Giảm tỷ trọng rủi ro, tăng tiền mặt & hedge" },
      { range: "76–100", level: "RỦI RO HỆ THỐNG",  action: "Hedge mạnh, chuyển danh mục phòng thủ toàn phần" },
    ],

    // Table headers
    th_category:  "Hạng mục",
    th_indicator: "Chỉ báo",
    th_value:     "Giá trị hiện tại",
    th_trend:     "Xu hướng 1 tuần",
    th_threshold: "Ngưỡng cảnh báo",
    th_status:    "Trạng thái",

    // Loading / error
    loading_text: "Đang tải dữ liệu thị trường...",
    error_text:   "Không thể tải dữ liệu. Vui lòng thử lại sau.",

    // Legend
    legend_title: "CHÚ THÍCH TRẠNG THÁI",
    legend_items: [
      { label: "CẢNH BÁO",    desc: "Chỉ số đã vượt ngưỡng nguy hiểm. Cần theo dõi sát và cân nhắc điều chỉnh danh mục." },
      { label: "CẢNH GIÁC",   desc: "Chỉ số đang tiệm cận ngưỡng cảnh báo. Cần chú ý theo dõi thêm." },
      { label: "BÌNH THƯỜNG", desc: "Chỉ số trong vùng an toàn. Tiếp tục quan sát định kỳ." },
    ],
    source_label: "Nguồn dữ liệu",
    source_desc:  "Yahoo Finance (WTI, VIX, HYG, TLT, TNX, SPY options, ETF shares, DXY) · CFTC Legacy COT (S&P 500 E-mini) · NAAIM Exposure Index · AAII Sentiment Survey · Xung đột Hormuz cập nhật thủ công.",
    contact_text: "Mọi ý kiến đóng góp xin liên hệ:",
    contact_thanks: ", cảm ơn bạn.",

    // Status labels (from data.json)
    status: {
      "CẢNH BÁO":   "CẢNH BÁO",
      "CẢNH GIÁC":  "CẢNH GIÁC",
      "Bình thường":"Bình thường",
    },
    risk_levels: {
      "BÌNH THƯỜNG":    "BÌNH THƯỜNG",
      "CẢNH GIÁC":      "CẢNH GIÁC",
      "CẢNH BÁO CAO":   "CẢNH BÁO CAO",
      "RỦI RO HỆ THỐNG":"RỦI RO HỆ THỐNG",
    },

    // Indicator names
    indicators: {
      "Dầu WTI":                    "Dầu WTI",
      "Xung đột Hormuz":            "Xung đột Hormuz",
      "COT — Commercial Net":       "COT — Commercial Net",
      "ETF Flows (SPY+QQQ)":        "ETF Flows (SPY+QQQ)",
      "Sentiment (NAAIM vs AAII)":  "Sentiment (NAAIM vs AAII)",
      "VIX":                        "VIX",
      "VIX futures curve":          "VIX futures curve",
      "HYG/TLT ratio":              "HYG/TLT ratio",
      "Put/Call ratio":             "Put/Call ratio",
      "10-year yield":              "10-year yield",
      "2s10s spread":               "2s10s spread",
      "DXY (USD Index)":            "DXY (USD Index)",
    },
    categories: {
      "Địa chính trị":       "Địa chính trị",
      "Dòng tiền tổ chức":   "Dòng tiền tổ chức",
      "Thị trường":          "Thị trường",
      "Vĩ mô":               "Vĩ mô",
    },
  },

  en: {
    // Header
    page_title:       "Daily Market Monitor",
    page_subtitle_pre: "Last updated:",
    page_source:      "Source: Yahoo Finance · FRED",
    btn_refresh:      "Refresh",

    // Summary pills
    pill_danger:   (n) => `${n} Alert`,
    pill_warning:  (n) => `${n} Caution`,
    pill_success:  (n) => `${n} Normal`,

    // Risk card
    risk_title:       "TOTAL RISK SCORE",
    risk_history_label: "30-day Risk Score History",
    table_title:      "Risk Indicator Details",
    gl_0: "0–35 Safe",
    gl_1: "36–55 Caution",
    gl_2: "56–75 Alert",
    gl_3: "76–100 Danger",
    bd_geo:    "Geopolitical",
    bd_inst:   "Institutional Flow",
    bd_market: "Market",
    bd_macro:  "Macro",
    bd_mult:   "Amplifier",
    bd_leads_title: "Active lead indicators:",

    // Lead indicator text translation (generated by Python, need frontend translate)
    leads: {
      "COT short ròng > 70% đỉnh lịch sử":     "COT short positioning > 70% of hist. peak",
      "VIX futures curve: Backwardation":        "VIX futures curve: Backwardation",
      "Dầu WTI > $100/thùng":                   "WTI Crude Oil > $100/barrel",
      "2s10s spread đảo ngược":                  "2s10s spread inverted",
      "ETF outflow > $5B/7d":                    "ETF outflow > $5B/7d",
    },
    bd_geo_w:    "(15%)",
    bd_inst_w:   "(25%)",
    bd_market_w: "(40%)",
    bd_macro_w:  "(20%)",

    // Risk table
    risk_th_range:  "Score range",
    risk_th_meaning:"Meaning",
    risk_th_action: "Action",
    risk_rows: [
      { range: "0–35",   level: "NORMAL",          action: "Maintain allocation, monitor regularly" },
      { range: "36–55",  level: "CAUTION",          action: "Reduce leverage, prepare hedges" },
      { range: "56–75",  level: "HIGH ALERT",       action: "Reduce risk exposure, increase cash & hedge" },
      { range: "76–100", level: "SYSTEMIC RISK",    action: "Activate full hedge, shift to defensive portfolio" },
    ],

    // Table headers
    th_category:  "Category",
    th_indicator: "Indicator",
    th_value:     "Current value",
    th_trend:     "1-week trend",
    th_threshold: "Alert threshold",
    th_status:    "Status",

    // Loading / error
    loading_text: "Loading market data...",
    error_text:   "Failed to load data. Please try again later.",

    // Legend
    legend_title: "STATUS LEGEND",
    legend_items: [
      { label: "ALERT",   desc: "Indicator has breached a danger threshold. Monitor closely and consider portfolio adjustment." },
      { label: "CAUTION", desc: "Indicator is approaching the alert threshold. Keep a close eye on developments." },
      { label: "NORMAL",  desc: "Indicator is within the safe zone. Continue periodic monitoring." },
    ],
    source_label: "Data sources",
    source_desc:  "Yahoo Finance (WTI, VIX, HYG, TLT, TNX, SPY options, ETF shares, DXY) · CFTC Legacy COT (S&P 500 E-mini) · NAAIM Exposure Index · AAII Investor Sentiment Survey · Strait of Hormuz updated manually.",
    contact_text: "Feedback & suggestions:",
    contact_thanks: ", thank you.",

    // Status labels
    status: {
      "CẢNH BÁO":   "ALERT",
      "CẢNH GIÁC":  "CAUTION",
      "Bình thường":"Normal",
    },
    risk_levels: {
      "BÌNH THƯỜNG":    "NORMAL",
      "CẢNH GIÁC":      "CAUTION",
      "CẢNH BÁO CAO":   "HIGH ALERT",
      "RỦI RO HỆ THỐNG":"SYSTEMIC RISK",
    },

    // Indicator names
    indicators: {
      "Dầu WTI":                   "WTI Crude Oil",
      "Xung đột Hormuz":           "Hormuz Conflict",
      "COT — Commercial Net":      "COT — Commercial Net",
      "ETF Flows (SPY+QQQ)":       "ETF Flows (SPY+QQQ)",
      "Sentiment (NAAIM vs AAII)": "Sentiment (NAAIM vs AAII)",
      "VIX":                       "VIX",
      "VIX futures curve":         "VIX futures curve",
      "HYG/TLT ratio":             "HYG/TLT ratio",
      "Put/Call ratio":            "Put/Call ratio",
      "10-year yield":             "10-year yield",
      "2s10s spread":              "2s10s spread",
      "DXY (USD Index)":           "DXY (USD Index)",
    },
    categories: {
      "Địa chính trị":     "Geopolitical",
      "Dòng tiền tổ chức": "Institutional Flow",
      "Thị trường":        "Market",
      "Vĩ mô":             "Macro",
    },

    // Translate value/threshold strings from Vietnamese → English
    // Used for exact matches (thresholds) and substring replacement (values)
    thresholds: {
      ">95 USD/thùng":              ">95 USD/barrel",
      "Có phong tỏa":               "Blockade detected",
      "Short > 70% đỉnh lịch sử":  "Short > 70% of hist. peak",
      "Outflow > −2B USD/7d":       "Outflow > −2B USD/7d",
      "Retail − Inst > +25pp":      "Retail − Inst > +25pp",
      ">30":                        ">30",
      "Backwardation":              "Backwardation",
      "Giảm >5%/tuần":              "Decline >5%/week",
      ">1.1":                       ">1.1",
      ">4.5%":                      ">4.5%",
      "Đảo ngược âm":               "Negative inversion",
      ">107":                       ">107",
    },
    // Substring replacements applied to value strings
    value_replace: [
      ["/thùng",           "/barrel"],
      ["thùng",            "barrel"],
      ["của đỉnh lịch sử", "of hist. peak"],
      ["đỉnh lịch sử",     "hist. peak"],
      ["Căng thẳng leo thang",      "Escalating tension"],
      ["Phong tỏa hoàn toàn",       "Full blockade"],
      ["Phong tỏa một phần / tàu bị tấn công", "Partial blockade / vessel attack"],
      ["Có đề cập — theo dõi thêm", "Mentioned — monitor closely"],
      ["Bình thường",               "Normal"],
      ["Chưa phong tỏa",            "No blockade"],
      ["Đang tích lũy (~5 ngày để có baseline)", "Accumulating (~5 days for baseline)"],
      ["Đang theo dõi",             "Monitoring"],
      ["Contango nhẹ",              "Light contango"],
      ["Backwardation mạnh",        "Deep backwardation"],
      ["Backwardation",             "Backwardation"],
      ["Phẳng",                     "Flat"],
    ],
  },
};

// ===== LANGUAGE STATE =====
let currentLang = localStorage.getItem("lang") || "vi";

function setLang(lang) {
  currentLang = lang;
  try { localStorage.setItem("lang", lang); } catch(e) {}
  document.documentElement.setAttribute("lang", lang === "vi" ? "vi" : "en");
  applyLang();
  updateLangToggle();
}

function t(key, ...args) {
  const val = I18N[currentLang]?.[key] ?? I18N["vi"]?.[key];
  return typeof val === "function" ? val(...args) : (val ?? key);
}

function applyLang() {
  const L = I18N[currentLang];
  if (!L) return;

  // Static text elements
  const set = (id, text) => { const el = document.getElementById(id); if (el) el.textContent = text; };
  const setHTML = (id, html) => { const el = document.getElementById(id); if (el) el.innerHTML = html; };

  set("page-title",        L.page_title);
  set("page-subtitle-pre", L.page_subtitle_pre);
  set("page-source-note",  L.page_source);
  set("risk-title",        L.risk_title);
  set("risk-history-label",L.risk_history_label);
  set("table-title",       L.table_title);

  // Gauge legend
  if (L.gl_0) set("gl-0", L.gl_0);
  if (L.gl_1) set("gl-1", L.gl_1);
  if (L.gl_2) set("gl-2", L.gl_2);
  if (L.gl_3) set("gl-3", L.gl_3);
  set("bd-geo-label",      `${L.bd_geo} <small>${L.bd_geo_w}</small>`);
  set("bd-market-label",   `${L.bd_market} <small>${L.bd_market_w}</small>`);
  set("bd-macro-label",    `${L.bd_macro} <small>${L.bd_macro_w}</small>`);

  // Use innerHTML for labels with <small>
  const setInner = (id, html) => { const el = document.getElementById(id); if (el) el.innerHTML = html; };
  setInner("bd-geo-label",    `${L.bd_geo} <small>${L.bd_geo_w}</small>`);
  setInner("bd-inst-label",   `${L.bd_inst} <small>${L.bd_inst_w}</small>`);
  setInner("bd-market-label", `${L.bd_market} <small>${L.bd_market_w}</small>`);
  setInner("bd-macro-label",  `${L.bd_macro} <small>${L.bd_macro_w}</small>`);
  set("bd-mult-label",        L.bd_mult);
  set("risk-leads-label",     `⚡ ${L.bd_leads_title || 'Lead indicators kích hoạt:'}`);

  // Table headers
  set("th-category",  L.th_category);
  set("th-indicator", L.th_indicator);
  set("th-value",     L.th_value);
  set("th-trend",     L.th_trend);
  set("th-threshold", L.th_threshold);
  set("th-status",    L.th_status);

  // Risk table headers
  set("risk-th-range",   L.risk_th_range);
  set("risk-th-meaning", L.risk_th_meaning);
  set("risk-th-action",  L.risk_th_action);

  // Risk table rows
  L.risk_rows.forEach((row, i) => {
    set(`risk-row-level-${i}`, row.level);
    set(`risk-row-action-${i}`, row.action);
  });

  // Legend
  set("legend-title", L.legend_title);
  L.legend_items.forEach((item, i) => {
    set(`legend-label-${i}`, item.label);
    set(`legend-desc-${i}`,  item.desc);
  });
  set("source-label", L.source_label);
  set("source-desc",  L.source_desc);
  set("contact-text", L.contact_text);
  set("contact-thanks", L.contact_thanks);

  // Refresh button label
  const refreshLabel = document.getElementById("refresh-label");
  if (refreshLabel) refreshLabel.textContent = L.btn_refresh;

  // Re-render dynamic content if data is loaded
  if (window._lastData) renderAll(window._lastData);
}

function updateLangToggle() {
  const btn = document.getElementById("lang-toggle");
  if (!btn) return;
  btn.textContent = currentLang === "vi" ? "EN" : "VI";
  btn.setAttribute("title", currentLang === "vi" ? "Switch to English" : "Chuyển sang tiếng Việt");
}
